$wallpaper = /home/ale/wallpapers/GTR.jpg
$background = rgb(0f0f12)
$foreground = rgb(afbcc6)
$color0 = rgb(0f0f12)
$color1 = rgb(474A57)
$color2 = rgb(4D5769)
$color3 = rgb(5F6574)
$color4 = rgb(9F5F74)
$color5 = rgb(3C5B84)
$color6 = rgb(61738B)
$color7 = rgb(afbcc6)
$color8 = rgb(7a838a)
$color9 = rgb(474A57)
$color10 = rgb(4D5769)
$color11 = rgb(5F6574)
$color12 = rgb(9F5F74)
$color13 = rgb(3C5B84)
$color14 = rgb(61738B)
$color15 = rgb(afbcc6)
