$wallpaper = /home/ale/wallpapers/Cat-2.jpg
$background = rgb(070D13)
$foreground = rgb(e4dfd0)
$color0 = rgb(070D13)
$color1 = rgb(69798B)
$color2 = rgb(788690)
$color3 = rgb(798CA3)
$color4 = rgb(8C9390)
$color5 = rgb(A4A9A5)
$color6 = rgb(C2BDAE)
$color7 = rgb(e4dfd0)
$color8 = rgb(9f9c91)
$color9 = rgb(69798B)
$color10 = rgb(788690)
$color11 = rgb(798CA3)
$color12 = rgb(8C9390)
$color13 = rgb(A4A9A5)
$color14 = rgb(C2BDAE)
$color15 = rgb(e4dfd0)
