$wallpaper = /home/ale/wallpapers/Snoopy.jpg
$background = rgb(060607)
$foreground = rgb(e1e0dd)
$color0 = rgb(060607)
$color1 = rgb(A9A196)
$color2 = rgb(D4BD99)
$color3 = rgb(CABBA5)
$color4 = rgb(D8C29D)
$color5 = rgb(DBC8A8)
$color6 = rgb(E2D0B2)
$color7 = rgb(e1e0dd)
$color8 = rgb(9d9c9a)
$color9 = rgb(A9A196)
$color10 = rgb(D4BD99)
$color11 = rgb(CABBA5)
$color12 = rgb(D8C29D)
$color13 = rgb(DBC8A8)
$color14 = rgb(E2D0B2)
$color15 = rgb(e1e0dd)
