services:
  ros2:
    build: .
    container_name: ros2_humble
    volumes:
      - ${ROS_WS_ROOT:-~/ros2-workspace}:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    privileged: true
